#!/usr/bin/env sh
# Sudoku solver
# by David Oniani <onianidavid@gmail.com>
# License: GNU GPLv3

python3 sudoku_to_dimacs.py "$1"
./ratsat --verb=0 sudoku.dimacs sudoku.solution
python3 display_solution.py < sudoku.solution
